application: warp-9
version: 1
runtime: go
api_version: go1

handlers:
- url: /dispatch
  script: _go_app

- url: /get
  script: _go_app

- url: /set
  script: _go_app

- url: /
  static_files: htdocs/index.html
  upload: htdocs/index.html

- url: /(.+)
  static_files: htdocs/\1
  upload: htdocs/.+